server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 169167866Spl.
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  data:
    redis:
      repositories:
        enabled: false

  # MyBatis-Plus 配置
  mybatis-plus:
    type-aliases-package: com.ws.po  # 实体类包名
    mapper-locations: classpath:mapper/*.xml  # Mapper XML 文件位置
    configuration:
      map-underscore-to-camel-case: true  # 下划线转驼峰
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 日志输出（SQL 显示）
  cache:
    type: redis
    redis:
      time-to-live: 600000  #缓存有效时长ms
      cache-null-values: false #是否允许空值
    cache-names: blog,tag,tag-name,type,type-name,user   #通过默认的RedisCacheManager在启动时创建其缓存空间

  redis:
    host: 101.42.176.44
    port: 6379
    password: 169167866Spl.
    timeout: 5000
    database: 0

logging:
  level:
    root: info
    com.lrm: debug
  file:
    path: log/blog-prod.log



